"""codeagent: a professional framework for building code development agents."""

from codeagent.core import (
    Agent,
    AgentConfig,
    AgentEvent,
    Budget,
    BudgetExceededError,
    LLMResponse,
    MaxIterationsError,
    Message,
    Role,
    ToolCall,
    ToolResult,
    Usage,
)
from codeagent.llm import (
    AggregateError,
    AggregateProvider,
    AnthropicProvider,
    LLMProvider,
    OllamaProvider,
    OpenAIProvider,
    create_provider,
    list_providers,
    parse_provider_spec,
    register_provider,
)
from codeagent.blueprint import (
    ApprovalResult,
    Blueprint,
    BlueprintReport,
    BlueprintRunner,
    BlueprintSpecError,
    CycleError,
    Edge,
    Node,
    NodeKind,
    NodeResult,
    load_blueprint_yaml,
    parse_blueprint,
)
from codeagent.eval import EvalReport, EvalResult, EvalTask, evaluate, load_mbpp
from codeagent.harness import (
    AskHarnessTool,
    CliHarness,
    HarnessResult,
    discover_harnesses,
)
from codeagent.leader import (
    Leader,
    ProgressBoard,
    RunArchive,
    TaskRecord,
    WorkerConfig,
    load_workers_yaml,
)
from codeagent.memory import (
    CompactionConfig,
    ConversationCompactor,
    LocalMemoryStore,
    Memory,
    MemoryOperation,
    MemoryStore,
    SmartMemoryStore,
    memory_tools,
)
from codeagent.voice import (
    EMOTION_PROMPT_SUFFIX,
    ASRProvider,
    EdgeTTSProvider,
    Emotion,
    TTSProvider,
    VoiceChatLoop,
    WhisperASRProvider,
    parse_emotion,
)
from codeagent.court import (
    Court,
    CourtReport,
    CourtRole,
    ReviewRejectedError,
    SubTask,
    TaskState,
    TaskStateMachine,
)
from codeagent.xiaozhi import (
    ActivationRequiredError,
    XiaozhiClient,
    XiaozhiConfig,
    XiaozhiProtocol,
)
from codeagent.log import get_logger, setup_logging, tail_log
from codeagent.releases import RELEASES, Release, changelog_text, latest
from codeagent.repair import SelfDebugger, SelfDebugResult
from codeagent.settings import Settings
from codeagent.skills import Skill, SkillEvolver, SkillLibrary
from codeagent.security import (
    ApprovalDecision,
    PermissionPolicy,
    RiskLevel,
    classify_command,
)
from codeagent.tools import (
    BrowserTool,
    ComfyTool,
    DelegateTool,
    Tool,
    ToolRegistry,
    WebFetchTool,
    WebScrapeTool,
    default_tools,
    web_tools,
)

__version__ = "0.75.1"

__all__ = [
    "Agent",
    "AgentConfig",
    "AgentEvent",
    "AggregateError",
    "AggregateProvider",
    "ASRProvider",
    "ActivationRequiredError",
    "AnthropicProvider",
    "ApprovalDecision",
    "ApprovalResult",
    "AskHarnessTool",
    "Blueprint",
    "BlueprintReport",
    "BlueprintRunner",
    "BlueprintSpecError",
    "BrowserTool",
    "Budget",
    "BudgetExceededError",
    "ComfyTool",
    "CompactionConfig",
    "ConversationCompactor",
    "Court",
    "CourtReport",
    "CourtRole",
    "CycleError",
    "CliHarness",
    "EMOTION_PROMPT_SUFFIX",
    "Edge",
    "EdgeTTSProvider",
    "Emotion",
    "DelegateTool",
    "HarnessResult",
    "EvalReport",
    "EvalResult",
    "EvalTask",
    "LLMProvider",
    "LLMResponse",
    "Leader",
    "LocalMemoryStore",
    "MaxIterationsError",
    "Memory",
    "MemoryOperation",
    "MemoryStore",
    "Message",
    "Node",
    "NodeKind",
    "NodeResult",
    "OllamaProvider",
    "OpenAIProvider",
    "PermissionPolicy",
    "ProgressBoard",
    "RELEASES",
    "Release",
    "ReviewRejectedError",
    "RiskLevel",
    "Role",
    "RunArchive",
    "SelfDebugger",
    "SelfDebugResult",
    "Settings",
    "Skill",
    "SkillEvolver",
    "SkillLibrary",
    "SmartMemoryStore",
    "SubTask",
    "TTSProvider",
    "TaskRecord",
    "TaskState",
    "TaskStateMachine",
    "Tool",
    "ToolCall",
    "ToolRegistry",
    "ToolResult",
    "Usage",
    "VoiceChatLoop",
    "WebFetchTool",
    "WebScrapeTool",
    "WhisperASRProvider",
    "WorkerConfig",
    "XiaozhiClient",
    "XiaozhiConfig",
    "XiaozhiProtocol",
    "changelog_text",
    "classify_command",
    "create_provider",
    "default_tools",
    "discover_harnesses",
    "evaluate",
    "get_logger",
    "latest",
    "list_providers",
    "parse_provider_spec",
    "load_blueprint_yaml",
    "load_mbpp",
    "load_workers_yaml",
    "memory_tools",
    "parse_blueprint",
    "register_provider",
    "setup_logging",
    "tail_log",
    "web_tools",
]
