#!/usr/bin/env python3
"""Generate in-app brand logo data URIs from logo-color.png.

成品方标（大部分像素不透明）浅色/深色共用同一张，避免重着色洗掉渐变。
细字标仍会生成一版浅色文字，供深色侧栏使用。
"""

from __future__ import annotations

import base64
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
SRC = HERE / "logo-color.png"

# 侧栏可用宽度约 196px，2x 视网膜渲染用 400px 宽足够清晰
URI_WIDTH = 400
# 深色主题中文字目标色（接近 --text 的浅色）
LIGHT_INK = (232, 234, 242)


def is_full_bleed_icon(img: Image.Image) -> bool:
    """铺满画布的应用图标（相对细字标）不能做深色重着色，否则渐变会被洗掉。"""
    alpha = img.convert("RGBA").split()[3]
    hist = alpha.histogram()
    opaque = sum(hist[200:])
    return opaque / float(img.width * img.height) > 0.55


def has_transparent_corners(img: Image.Image) -> bool:
    """四角透明：成品字标 / 带透明底的 CCA，浅色深色共用，勿重着色。"""
    rgba = img.convert("RGBA")
    w, h = rgba.size
    px = rgba.load()
    for x, y in ((2, 2), (w - 3, 2), (2, h - 3), (w - 3, h - 3)):
        if px[x, y][3] >= 16:
            return False
    return True


def to_dark_theme(src: Image.Image) -> Image.Image:
    """把深色（近黑/藏青）像素平滑重映射为浅灰，彩色像素保持不变。"""
    img = src.convert("RGBA")
    px = img.load()
    for y in range(img.height):
        for x in range(img.width):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            lum = 0.299 * r + 0.587 * g + 0.114 * b
            # 饱和度：彩色像素（橙红徽标）不动
            mx, mn = max(r, g, b), min(r, g, b)
            sat = 0 if mx == 0 else (mx - mn) / mx
            if sat > 0.35:
                continue
            # lum < 60 → 完全替换；60~150 平滑过渡；>150 保留（白色高光）
            t = min(max((lum - 60) / 90.0, 0.0), 1.0)
            nr = int(LIGHT_INK[0] * (1 - t) + r * t)
            ng = int(LIGHT_INK[1] * (1 - t) + g * t)
            nb = int(LIGHT_INK[2] * (1 - t) + b * t)
            px[x, y] = (nr, ng, nb, a)
    return img


def uri_of(img: Image.Image, width: int) -> str:
    h = round(img.height * width / img.width)
    small = img.resize((width, h), Image.LANCZOS)
    import io

    buf = io.BytesIO()
    small.save(buf, format="PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def main() -> int:
    if not SRC.is_file():
        raise SystemExit(f"missing artwork: {SRC}")
    src = Image.open(SRC).convert("RGBA")
    # 成品方标 / 透明底字标：浅色深色侧栏共用，避免重着色洗掉 CCA 渐变。
    keep = is_full_bleed_icon(src) or has_transparent_corners(src)
    dark = src.copy() if keep else to_dark_theme(src)
    dark.save(HERE / "logo-color-dark.png")
    print(f"OK → {HERE / 'logo-color-dark.png'} (same_as_light={keep})")

    out = ROOT / "src" / "codeagent" / "desktop" / "brand_logo.py"
    out.write_text(
        '"""In-app brand logo as data URIs (generated by packaging/make_brand_logo.py).\n\n'
        "成品方标或透明底字标时浅色与深色使用同一张图；细字黑标才会分成两版。\n"
        '"""\n\n'
        f"LOGO_URI_LIGHT = {uri_of(src, URI_WIDTH)!r}\n\n"
        f"LOGO_URI_DARK = {uri_of(dark, URI_WIDTH)!r}\n",
        encoding="utf-8",
    )
    print(f"OK → {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
