#!/usr/bin/env python3
"""Build CodeCoreAgent icons from the painted CCA emblem (logo-art.png)."""

from __future__ import annotations

import base64
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ART = HERE / "logo-art.png"
SIZE = 1024


def rounded_mask(size: int, radius: int) -> Image.Image:
    m = Image.new("L", (size, size), 0)
    ImageDraw.Draw(m).rounded_rectangle(
        [0, 0, size - 1, size - 1], radius=radius, fill=255
    )
    return m.filter(ImageFilter.GaussianBlur(0.6))


def fit_art(src: Image.Image, size: int) -> Image.Image:
    src = src.convert("RGBA")
    side = min(src.size)
    left = (src.width - side) // 2
    top = (src.height - side) // 2
    src = src.crop((left, top, left + side, top + side))
    return src.resize((size, size), Image.LANCZOS)


def render() -> Image.Image:
    if not ART.is_file():
        raise SystemExit(f"missing artwork: {ART}")
    art = fit_art(Image.open(ART), SIZE)
    art.putalpha(rounded_mask(SIZE, int(SIZE * 0.22)))
    return art


def make_icns(png: Path, out: Path) -> None:
    with tempfile.TemporaryDirectory() as td:
        iconset = Path(td) / "icon.iconset"
        iconset.mkdir()
        for size in (16, 32, 64, 128, 256, 512):
            img = Image.open(png).resize((size, size), Image.LANCZOS)
            img.save(iconset / f"icon_{size}x{size}.png")
            img2x = Image.open(png).resize((size * 2, size * 2), Image.LANCZOS)
            img2x.save(iconset / f"icon_{size}x{size}@2x.png")
        subprocess.run(["iconutil", "-c", "icns", str(iconset), "-o", str(out)],
                       check=True)


def make_ico(png: Path, out: Path) -> None:
    Image.open(png).save(
        out,
        sizes=[(16, 16), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)],
    )


def write_sidebar_mark(master: Image.Image) -> None:
    mark = master.resize((96, 96), Image.LANCZOS)
    dest = HERE / "mark.png"
    mark.save(dest, optimize=True)
    uri = "data:image/png;base64," + base64.b64encode(dest.read_bytes()).decode("ascii")
    out = ROOT / "src" / "codeagent" / "desktop" / "brand_mark.py"
    out.write_text(
        '"""Sidebar mark as a data URI (generated by packaging/make_icon.py)."""\n\n'
        f"MARK_URI = {uri!r}\n",
        encoding="utf-8",
    )
    print(f"OK → {dest}")
    print(f"OK → {out}")


def main() -> int:
    master = render()
    png = HERE / "icon.png"
    master.save(png)
    print(f"OK → {png}")
    write_sidebar_mark(master)
    if sys.platform == "darwin":
        make_icns(png, HERE / "icon.icns")
        print(f"OK → {HERE / 'icon.icns'}")
    make_ico(png, HERE / "icon.ico")
    print(f"OK → {HERE / 'icon.ico'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
